stages:
 - test
 - deploy
pre-deploy:
 stage: test
 script: echo "Deploying to Dev Notification API"
deploy:
 stage: deploy
 script:
 - cd /opt/devapi
 - sudo git stash
 - sudo git pull origin development
 - sudo chown -R gitlab-runner:root /opt/devapi
 only:
 - development
