image: alpine

stages:
  - deployment

deploy:
  stage: deployment
  before_script:
      - apk add openssh-client
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
      - mkdir -p ~/.ssh
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh ubuntu@$SERVER_IP "cd /home/ubuntu/test && touch test.txt"
  only:
    - master 
