stages:
 - test
 - deploy
test:
 stage: test
 script: echo "Running tests"
#deploy_test:
# stage: deploy
# script:
# - cd /opt/manual
# - sudo git stash
# - sudo git pull origin master
 only:
 - master 
