stages:
 - test
 - deploy
test:
 stage: test
 script: echo "Deploying to Notification API"
deploy_test:
 stage: deploy
 script:
 - cd /opt/notificationapi
 - sudo git stash
 - sudo git pull origin master
 - sudo chown -R gitlab-runner:root /opt/notificationapi
 - sudo su
 - sudo pm2 restart app
 only:
 - master 
